CREATE TABLE CLIENT (
	ID_CLIENT SERIAL PRIMARY KEY NOT NULL,
	CLIENT_NAME VARCHAR(30) NOT NULL,
	CLIENT_LAST_NAME VARCHAR(30) NOT NULL,
	CLIENT_EMAIL VARCHAR(100) NOT NULL,
	CLIENT_ADDRESS VARCHAR(100) NOT NULL,
	CLIENT_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE WISH (
	ID_WISH SERIAL PRIMARY KEY NOT NULL,
	FK_CLIENT INTEGER NOT NULL,
	WISH_DATE DATE NOT NULL,
	WISH_STATE VARCHAR(10) NOT NULL,
	WISH_TOTAL FLOAT NOT NULL,
	CONSTRAINT FK_CLIENT_WISH FOREIGN KEY (FK_CLIENT) REFERENCES CLIENT (ID_CLIENT)
);

CREATE TABLE PRODUCT (
	ID_PRODUCT SERIAL PRIMARY KEY NOT NULL,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PRODUCT_DESCRIPTION VARCHAR(200) NOT NULL,
	PRODUCT_UNIT_PRICE FLOAT NOT NULL
);

CREATE TABLE WISH_DETAIL (
	ID_WISH_DETAIL SERIAL PRIMARY KEY NOT NULL,
	FK_WISH INTEGER NOT NULL,
	FK_PRODUCT INTEGER NOT NULL,
	WISH_DETAIL_AMOUNT INT NOT NULL,
	WISH_DETAIL_SUBTOTAL FLOAT NOT NULL,
	CONSTRAINT FK_WISHDETAIL_WISH FOREIGN KEY (FK_WISH) REFERENCES WISH (ID_WISH),
	CONSTRAINT FK_WISHDETAIL_PRODUCT FOREIGN KEY (FK_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
);

CREATE TABLE WISH_HISTORY (
	ID_WISH_HISTORY SERIAL PRIMARY KEY NOT NULL,
	FK_WISH INTEGER NOT NULL,
	WISH_HISTORY_DATE DATE NOT NULL,
	WISH_HISTORY_STATE VARCHAR(10) NOT NULL,
	WISH_HISTORY_FINAL_PRICE FLOAT NOT NULL,
	CONSTRAINT FK_WISHHISTORY_WISH FOREIGN KEY (FK_WISH) REFERENCES WISH (ID_WISH)
);

CREATE TABLE INTERNAL_USER (
	ID_INTERNAL_USER SERIAL PRIMARY KEY NOT NULL,
	INTERNAL_USER_NAME VARCHAR(30) NOT NULL,
	INTERNAL_USER_PASSWORD VARCHAR(100) NOT NULL,
	INTERNAL_USER_ROLE VARCHAR(30) NOT NULL
);

CREATE TABLE MAIL (
	ID_MAIL SERIAL PRIMARY KEY NOT NULL,
	MAIL_TYPE VARCHAR(20) NOT NULL,
	MAIL_RECEIVER VARCHAR(50) NOT NULL,
	MAIL_CONTENT VARCHAR(300) NOT NULL
);

INSERT INTO CLIENT (CLIENT_NAME, CLIENT_LAST_NAME, CLIENT_EMAIL, CLIENT_ADDRESS, CLIENT_PASSWORD)
VALUES
('JUAN','PEREZ','JUANPEREZ@GMAIL.COM','LARREA_4646','123456789'),
('MARTA','JUANA','MARTA@GMAIL.COM','LARREA_4645','12345678'),
('MARTINA','MORENA','MORENA@GMAIL.COM','LARREA_4644','1234567'),
('LIONEL','PEREZ','LIO@GMAIL.COM','LARREA_4643','123456');

INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_UNIT_PRICE)
VALUES
('paquete a Rio de Janeiro','Viaje fantastico para 2', 450000),
('paquete a España','Viaje fantastico para adultos', 550000),
('paquete a Puerto Rico','hermosas vistas', 700000),
('paquete a Peru','bueno, bonito y barato', 250000);
